name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          mkdir temp
          cp -r . temp/

      - name: Remove excluded files
        run: |
          while IFS= read -r pattern; do
            if [[ "$pattern" == *"*"* ]]; then
              find temp -name "$pattern" -exec rm -rf {} +
            else
              rm -rf temp/$pattern
            fi
          done < .github/exclude.txt

      - name: Debug file sizes
        run: |
          echo "File size of release.zip before zipping: $(du -sh temp | cut -f1)"

      - name: Zip files
        run: |
          cd temp
          zip -r ../release.zip .
          cd ..

      - name: Check file size
        run: |
          FILE_SIZE=$(stat -c%s "./release.zip")
          MAX_SIZE=$((2 * 1024 * 1024 * 1024)) # 2 GiB in bytes
          echo "File size of release.zip: $FILE_SIZE bytes"
          if [ "$FILE_SIZE" -gt "$MAX_SIZE" ]; then
            echo "Error: File size ($FILE_SIZE) exceeds the maximum allowed size of 2 GiB."
            exit 1
          fi

      - name: Get release upload URL
        id: get_release
        uses: actions/github-script@v5
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.release.tag_name
            });
            // Rimuove "{?name,label}" dall'URL e imposta come output
            return release.data.upload_url.split('{')[0];
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug upload URL
        run: |
          echo "Upload URL: ${{ steps.get_release.outputs.upload_url }}"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: cleaned_release.zip
          asset_content_type: application/zip
