name: Clean Release ZIP

on:
  release:
    types: [published]

jobs:
  remove_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Remove files and folders listed in .github/exclude.txt
      run: |
        zip_file="release.zip"
        mkdir temp
        cp -r . temp/
        # Rimuovi i file specificati in .github/exclude.txt
        while IFS= read -r pattern; do
          if [[ "$pattern" == *"*"* ]]; then
            find temp -name "$pattern" -exec rm -rf {} +
          else
            rm -rf temp/$pattern
          fi
        done < .github/exclude.txt
        cd temp
        zip -r ../$zip_file .
        cd ..

    - name: Upload cleaned ZIP to release
      uses: actions/upload-release-asset@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_id: ${{ github.event.release.id }}
        asset_path: ./release.zip
        asset_name: cleaned_release.zip
        asset_content_type: application/zip
