name: Create Cleaned Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove files and folders listed in .github/exclude.txt
      run: |
        zip_file="release.zip"
        mkdir temp
        rsync -av --exclude=temp . temp/
        while IFS= read -r pattern; do
          if [[ "$pattern" == *"*"* ]]; then
            find temp -name "$pattern" -exec rm -rf {} +
          else
            rm -rf temp/$pattern
          fi
        done < .github/exclude.txt
        cd temp
        zip -r ../$zip_file .
        cd ..

    - name: Get release upload URL
      id: get_release
      uses: actions/github-script@v5
      with:
        script: |
          const release = await github.rest.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: context.payload.release.tag_name
          });
          // Rimuove "{?name,label}" dall'URL e imposta come output
          core.setOutput('upload_url', release.data.upload_url.split('{')[0]);

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: cleaned_release.zip
        asset_content_type: application/zip
